name: tma_data_extraction
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - tornado
  - pcre2
  - graphite2
  - matplotlib-base
  - xorg-libxrender
  - pyproj
  - pillow
  - giflib
  - snappy
  - gsl
  - readline
  - libgfortran-ng
  - r-rpart
  - r-spatial
  - r-lattice
  - xorg-libxau
  - cloudpickle
  - libnetcdf
  - openjpeg
  - pyepsg
  - xorg-inputproto
  - liblapack
  - brotlipy
  - glib
  - python-dateutil
  - yaml
  - proj
  - r-cluster
  - statsmodels
  - r-mgcv
  - r-codetools
  - cairo
  - lcms2
  - pyyaml
  - idna
  - networkx
  - harfbuzz
  - python_abi
  - numpy
  - xorg-renderproto
  - r-base
  - hdf4
  - r-nnet
  - shapely
  - cftime
  - lerc
  - xorg-xextproto
  - cryptography
  - openssl
  - gxx_linux-64
  - gcc_impl_linux-64
  - tk
  - scipy
  - r-purrr
  - binutils_impl_linux-64
  - seaborn-base
  - requests
  - urllib3
  - freetype
  - libaec
  - xorg-xproto
  - pycparser
  - pthread-stubs
  - sed
  - geos
  - icu
  - r-mass
  - libgomp
  - gxx_impl_linux-64
  - r-boot
  - pixman
  - r-nlme
  - curl
  - poppler-data
  - brotli
  - setuptools
  - dask-core
  - zstd
  - ncurses
  - pcre
  - fribidi
  - charls
  - xorg-libice
  - xorg-libxfixes
  - basemap
  - libxcb
  - netcdf4
  - libbezier
  - bwidget
  - olefile
  - zfp
  - gcc_linux-64
  - gfortran_linux-64
  - hdf5
  - libblas
  - libwebp-base
  - libssh2
  - r-recommended
  - xorg-fixesproto
  - imageio
  - pyopenssl
  - xorg-libxext
  - krb5
  - libffi
  - fontconfig
  - libgcc-ng
  - r-stringr
  - libxml2
  - gfortran_impl_linux-64
  - decorator
  - libuuid
  - poppler
  - binutils_linux-64
  - _r-mutex
  - cycler
  - jxrlib
  - r-kernsmooth
  - ca-certificates
  - mupdf
  - tifffile
  - libedit
  - pykdtree
  - sqlite
  - xorg-libsm
  - seaborn
  - r-foreign
  - r-class
  - freeglut
  - bzip2
  - matplotlib
  - pywavelets
  - pango
  - r-dplyr
  - xorg-libxdmcp
  - pyparsing
  - libzopfli
  - make
  - xz
  - six
  - libcurl
  - jpeg
  - pysocks
  - xorg-libxi
  - libstdcxx-ng
  - owslib
  - xorg-kbproto
  - certifi
  - kiwisolver
  - python
  - xorg-libx11
  - lz4-c
  - imagecodecs
  - patsy
  - blosc
  - jbig2dec
  - libcblas
  - r
  - scikit-image
  - cartopy
  - xarray
  - libpng
  - libopenblas
  - pytz
  - libiconv
  - pandas
  - _openmp_mutex
  - libtiff
  - ld_impl_linux-64
  - cytoolz
  - brunsli
  - toolz
  - pyshp
  - chardet
  - r-survival
  - r-pdftools
  - zlib
  - gettext
  - wheel
  - cffi
  - r-matrix
  - pip
  - tktable
  - nano
