name: tma_data_extraction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pip
  - numpy
  - libbezier
  - matplotlib
  - cartopy
  - scikit-image
  - r-base
  - r-stringr
  - r-purrr
  - r-pdftools
  - r-dplyr
  - xarray
  - pip:
    - bezier
  - netcdf4
